-- MasjidCMS database schema is managed exclusively by CodeIgniter migrations.
--
-- This file is intentionally non-executable. It exists only as a compatibility
-- marker for older documentation and tooling that referenced database/schema.sql.
--
-- Do not import this file into MySQL/MariaDB.
-- Use:
--   php spark migrate
--
-- Source of truth:
--   app/Database/Migrations/
