-- MasjidCMS seed data is managed exclusively by CodeIgniter seeders.
--
-- This file is intentionally non-executable. It exists only as a compatibility
-- marker for older documentation and tooling that referenced database/seed.sql.
--
-- Do not import this file into MySQL/MariaDB.
-- Use the installer, or run the relevant seeders explicitly, for example:
--   php spark db:seed RbacSeeder
--   php spark db:seed MasjidSeeder
--   php spark db:seed FinancialSeeder
--
-- Source of truth:
--   app/Database/Seeds/
